displayName: WebSphere Liberty MicroProfile® 
description: Eclipse MicroProfile® on Websphere Liberty
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "liberty"
language: "java"
