displayName: Python
description: HelloWorld microservice written in python
tags: ["python", "docker"]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "docker"
language: "python"
